name: Integration Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 21
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: klimaralley
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --silent" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - name: Create empty schema
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root --password= klimaralley << EOF
        CREATE DATABASE IF NOT EXISTS klimaralley;
        USE klimaralley;
        EOF

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '21'
        architecture: 'x64'

    - name: Install Python and dependencies
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install pytest
      run: |
        pip install pytest
        pip install requests

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Start the Spring Boot application
      run: java -jar target/klimaralley.server-*.jar &

    - name: Wait for application to start
      run: |
        while ! curl --output /dev/null --silent --head --fail http://localhost:8080/health/; do
          printf '.'
          sleep 10
        done
        echo "Application is up and running"

    - name: Run integration tests
      run: |
        pytest ./test/test.py
