name: Integration Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 21
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: klimaralley
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --silent" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout Klimaralley SQL repository
      uses: actions/checkout@v3
      with:
        repository: j0giwa/klimaralley
        path: klimaralley-repo

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -u root --silent; do
          echo 'Waiting for MySQL...'
          sleep 5
        done
      shell: bash

    - name: Import SQL file into MySQL
      run: |
        mysql -h 127.0.0.1 -u root klimaralley < klimaralley-repo/database/klimaralley.sql
      shell: bash

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'
        architecture: 'x64'

    - name: Install Python and dependencies
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pytest
      run: |
        pip install pytest
        pip install requests

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
      id: build_step

    - name: Start the Spring Boot application
      run: java -jar target/klimaralley.server-*.jar &
      if: steps.build_step.conclusion == 'success'
      id: start_application
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/klimaralley
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ""

    - name: Wait for application to start
      run: |
        while ! curl --output /dev/null --silent --head --fail http://localhost:8080/health/; do
          sleep 15
        done
        echo "Application is up and running"
      if: steps.start_application.conclusion == 'success'

    - name: Run integration tests
      run: pytest ./test/test.py
      if: steps.start_application.conclusion == 'success'
