name: Integration Test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: klimaralley
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Run MySQL client to create schema
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root mydatabase < path/to/your/schema.sql

    - name: Start the Spring Boot application
      run: java -jar target/your-spring-boot-app.jar &

    - name: Wait for application to start
      run: sleep 30

    - name: Run integration tests
      run: |
        chmod +x ./test/test.sh
        ./test/test.sh

    - name: Stop the Spring Boot application
      run: pkill -f your-spring-boot-app.jar
